parameters:

services:
    sql:
        class: Utils\DB\SQL

    language:
        class: AppBundle\Entity\Language\LanguageRepository
        arguments: [@sql]

    author:
        class: AppBundle\Entity\Author\AuthorRepository
        arguments: [@sql, @language]
