services:
    sql:
        class: Utils\DB\SQL
        arguments:
            - '%database_host%'
            - '%database_name%'
            - '%database_user%'
            - '%database_password%'

    language:
        class: AppBundle\Entity\Language\LanguageRepository
        arguments: ['@sql']

    author:
        class: AppBundle\Entity\Author\AuthorRepository
        arguments: ['@sql', '@language']

    section:
        class: AppBundle\Entity\Section\SectionRepository
        arguments: ['@sql', '@language']

    book:
        class: AppBundle\Entity\Book\BookRepository
        arguments: ['@sql', '@author', '@language', '@section']

    parallango:
        class: AppBundle\Entity\Parallango\ParallangoRepository
        arguments: ['@sql', '@book']

    page_size:
        class: AppBundle\Entity\Page\PageSize\PageSizeRepository
        arguments: ['@sql']

    page:
        class: AppBundle\Entity\Page\PageRepository
        arguments: ['@sql', '%books_root%']

    twig.random_color:
        class: AppBundle\Resources\Twig\RandomColorExtension
        tags:
            - { name: twig.extension }

    language.current:
        class: AppBundle\Entity\Language\Language
        factory: ['@language', 'get']
        arguments: ['en']
