home:
    path: /
    defaults: { _controller: AppBundle:HomePage:index }

feedback:
    path: /feedback
    defaults: { _controller: AppBundle:Feedback:save }

registration:
    path: /registration
    defaults: { _controller: AppBundle:Registration:registerUser }

author:
    path: /author/{authorId}
    defaults: { _controller: AppBundle:Author:index }
    methods: [GET, POST]
    requirements:
        authorId: \d+

section:
    path: /section/{sectionId}
    defaults: { _controller: AppBundle:Section:index }
    methods: [GET, POST]
    requirements:
        sectionId: \d+

parallango:
    path: /book/{parallangoId}
    defaults: { _controller: AppBundle:Parallango:index }
    methods: [GET, POST]
    requirements:
        parallangoId: \d+

language_aware:
    path: /{_locale}{path}
    defaults: { _controller: AppBundle:LanguageAware:forward }
    methods: [GET, POST]
    requirements:
        _locale: en|ru
        path: .*

items:
    path: /{languageCode}/{itemsType}/{offset}
    defaults: { _controller: AppBundle:Items:index }
    methods: [POST]
    requirements:
        languageCode: (en|ru)
        itemsType: (author|section|parallango)
        offset: \d+
