home:
    path: /
    defaults: { _controller: AppBundle:HomePage:index }

feedback:
    path: /feedback
    defaults: { _controller: AppBundle:Feedback:save }

registration:
    path: /registration
    defaults: { _controller: AppBundle:Registration:registerUser }
