home:
    path: /
    defaults: { _controller: AppBundle:HomePage:index }

feedback:
    path: /feedback
    defaults: { _controller: AppBundle:Feedback:save }

registration:
    path: /registration
    defaults: { _controller: AppBundle:Registration:registerUser }

author:
    path: /author/{authorId}
    defaults: { _controller: AppBundle:Author:index }
    methods: [GET]
    requirements:
        authorId: \d+

section:
    path: /section/{sectionId}
    defaults: { _controller: AppBundle:Section:index }
    methods: [GET]
    requirements:
        sectionId: \d+

parallango1:
    path: /book/{parallangoId}
    defaults: { _controller: AppBundle:Parallango:index }
    methods: [GET]
    requirements:
        parallangoId: \d+
parallango2:
    path: /book/{parallangoId}/{pageNumber}
    defaults: { _controller: AppBundle:Parallango:index }
    methods: [GET]
    requirements:
        parallangoId: \d+
        pageNumber: \d+
parallango_ajax:
    path: /book/{parallangoId}/{pageNumber}
    defaults: { _controller: AppBundle:Parallango:ajax }
    methods: [POST]
    requirements:
        parallangoId: \d+
        pageNumber: \d+
